import type { NextPage } from 'next';
import Head from 'next/head';
import About from '../components/About';
import Articles from '../components/Articles';
import Header from '../components/Header';

const Home: NextPage = () => {
  return (
    <div id='home'>
      <Head>
        <title>Test Brilo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />

      <main className='container'>
        <About />
        <Articles />
      </main>

      <footer className='container p-5 text-center font-extralight'>
        <span>© Mykola Tokarskyi 2022</span>
      </footer>
    </div>
  );
};

export default Home;
